### ISSUE TITLE
Image saving in database ( MongoDB) regarding.

### ISSUE THREAD

**Issue by aruribadraiah** [predatorkill/ng2-forms-demo#11]
Dear efstathi,
thank you for your image upload project, I am doing well, But One problem I am facing No. of image files are increasing which leads file count in file system.  My request to you, if possible could you please give code for ( changes ) for storing the image in database. ( I have gone through project file structure, request for where could changes for storing images in database)
thank you very much in advance.

**Comment by efstathiosntonas** [comment]
If you want the images to be stored in the database, the database size will be bigger than the files size because they are stored in base64 format. (base64 files are 33% larger than normal binary like png/jpg) In general, storing images in databases is not a really good practice. 

Other than that, please use stackoverflow or find good tutorials on how to do this. It's not that hard with mongodb.

http://menge.io/2015/03/24/storing-small-images-in-mongodb/
