### ISSUE TITLE
Deploy your application to Heroku

### ISSUE THREAD

**Issue by alan345** [predatorkill/ng2-forms-demo#4]
Hi ! 
Is your repository compatible with Heroku?
If yes, how can set it up ?
Thanks

**Comment by efstathiosntonas** [comment]
Hi, this is something you need to figure out your own, there are plenty of tutorials on how to run node and mongo with heroku.

**Comment by alan345** [comment]
Hi, thanks for your message. I am not going to use Heroku, but a regular server.
on the server, `npm start` is running, 
If i run `ng build`, I get this screen, and nothing happen.
https://snag.gy/dQnji5.jpg

Do you know what I am doing wrong?

(it works perfectly on local)
Thanks again

**Comment by efstathiosntonas** [comment]
Do you have angular-cli installed globally with `npm install @angular/cli -g`?

I must update this repo, it's getting outdated but right now I'm into some other projects and I have really limited time.

**Comment by alan345** [comment]
sure I understand.. yes I have done : npm install @angular/cli -g

**Comment by efstathiosntonas** [comment]
The correct way on deploying in server is:

1. run `ng build --prod` in your local enviroment, this will create a dist folder
2. Take that dist folder and deploy it in your server via ftp or whatever suits you
3. edit your `www` file inside the bin folder to point in correct server folder like: `var app = require('../server/server');` on line 10
4. make sure all folders paths in server files are pointing in the right path, like `app.use(express.static(path.join(__dirname, '../dist')));` in `server.js` (you can also add all the folders path inside the config.js and call the folder you want by config.imagePath for example, this will make it easier to use them). Note that there are many paths that you must edit in order to work correctly, not just in `server.js`

See this screenshot on how the folders should be structured in a production server
<img width="214" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/717975/23812641/0c82f4cc-05e4-11e7-8db3-6278346d2daf.png">

5. install `pm2` module, read the documentation on how to start the server, it's a great module for production apps.

**Comment by alan345** [comment]
In your package.json, you have `"angular-cli": "1.0.0-beta.24",` Hence I did not use `npm install @angular/cli -g` but now, after relaunching `npm install @angular/cli -g`, I have:

```
/usr/local/lib/node_modules/@angular/cli/models/config/config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by efstathiosntonas** [comment]
read the previous comment, you must not build the app on server but in your local machine and then upload it.

**Comment by alan345** [comment]
great, I will investigate on your latest post ! THanks a lot

**Comment by alan345** [comment]
Great ! Just an advise, split your module file into many modules 
https://github.com/efstathiosntonas/ngx-form/blob/master/src/app/app.module.ts.
It is cleaner and you will be able to load lazy module in the future. 
Moreover, each module will be independant.

**Comment by efstathiosntonas** [comment]
The app is really small, no need for lazy loading. It's not that difficult to refactor the code and add lazy loading but i won't do it :)
